# fly.toml app configuration file generated for invoice-eye-sparkling-breeze-4945 on 2024-04-19T14:12:14+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'invoice-eye'
primary_region = 'ams'
swap_size_mb = 256

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
size = 'shared-cpu-1x'
